create table if not exists public.storage_snapshots (
  id bigint generated by default as identity primary key,
  captured_at timestamptz not null default now(),
  category text not null check (char_length(category) between 1 and 48),
  bytes_used bigint not null check (bytes_used >= 0),
  object_count bigint not null default 0 check (object_count >= 0),
  source text not null default 'manual' check (char_length(source) between 1 and 48)
);

create index if not exists storage_snapshots_captured_at_idx
  on public.storage_snapshots (captured_at desc);

alter table public.storage_snapshots enable row level security;

drop policy if exists "Public dashboard can read snapshots" on public.storage_snapshots;
create policy "Public dashboard can read snapshots"
  on public.storage_snapshots
  for select
  to anon, authenticated
  using (true);

-- Optional demo history: one row per category per day for the last 90 days.
insert into public.storage_snapshots
  (captured_at, category, bytes_used, object_count, source)
select
  date_trunc('day', now()) - (day_offset || ' days')::interval,
  category,
  round(base_bytes * (1 - day_offset * 0.003) * (0.97 + random() * 0.06))::bigint,
  round(base_objects * (1 - day_offset * 0.002) * (0.96 + random() * 0.08))::bigint,
  'demo-seed'
from generate_series(0, 89) as day_offset
cross join (
  values
    ('图片', 438000000000::numeric, 18420::numeric),
    ('视频', 812000000000::numeric, 2160::numeric),
    ('文档', 164000000000::numeric, 32180::numeric),
    ('备份', 326000000000::numeric, 184::numeric),
    ('日志', 98000000000::numeric, 894000::numeric)
) as categories(category, base_bytes, base_objects)
where not exists (select 1 from public.storage_snapshots limit 1);

create table if not exists public.monitors (
  id bigint generated by default as identity primary key,
  name text not null unique check (char_length(name) between 1 and 64),
  endpoint text not null check (char_length(endpoint) between 1 and 256),
  kind text not null default 'Web',
  region text not null default 'Global',
  enabled boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.monitor_checks (
  id bigint generated by default as identity primary key,
  monitor_id bigint not null references public.monitors(id) on delete cascade,
  checked_at timestamptz not null default now(),
  latency_ms integer not null check (latency_ms >= 0),
  status_code integer not null default 200,
  ok boolean not null default true
);

create index if not exists monitor_checks_monitor_time_idx
  on public.monitor_checks (monitor_id, checked_at desc);

create table if not exists public.incidents (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 160),
  monitor_name text not null,
  severity text not null default 'minor' check (severity in ('minor', 'major', 'critical')),
  status text not null default 'investigating' check (status in ('investigating', 'monitoring', 'resolved')),
  started_at timestamptz not null default now(),
  resolved_at timestamptz
);

alter table public.monitors enable row level security;
alter table public.monitor_checks enable row level security;
alter table public.incidents enable row level security;

drop policy if exists "Public dashboard can read monitors" on public.monitors;
create policy "Public dashboard can read monitors"
  on public.monitors for select to anon, authenticated using (true);

drop policy if exists "Public dashboard can read checks" on public.monitor_checks;
create policy "Public dashboard can read checks"
  on public.monitor_checks for select to anon, authenticated using (true);

drop policy if exists "Public dashboard can read incidents" on public.incidents;
create policy "Public dashboard can read incidents"
  on public.incidents for select to anon, authenticated using (true);

insert into public.monitors (name, endpoint, kind, region)
values
  ('主站', 'app.monitor.site', 'Web', 'Seoul'),
  ('数据 API', 'api.monitor.site/v1', 'API', 'Singapore'),
  ('身份认证', 'auth.monitor.site', 'Auth', 'Tokyo'),
  ('文件存储', 'cdn.monitor.site', 'Storage', 'Global')
on conflict (name) do nothing;

insert into public.monitor_checks (monitor_id, checked_at, latency_ms, status_code, ok)
select
  m.id,
  now() - (point * interval '5 minutes'),
  greatest(35, round(70 + m.id * 23 + random() * 48 + sin(point / 17.0) * 22))::integer,
  case when m.name = '数据 API' and point between 78 and 83 then 503 else 200 end,
  not (m.name = '数据 API' and point between 78 and 83)
from public.monitors m
cross join generate_series(0, 287) as point
where not exists (select 1 from public.monitor_checks limit 1);

insert into public.incidents
  (title, monitor_name, severity, status, started_at, resolved_at)
select
  'API 延迟短时升高',
  '数据 API',
  'minor',
  'resolved',
  now() - interval '7 hours 6 minutes',
  now() - interval '6 hours 33 minutes'
where not exists (select 1 from public.incidents limit 1);

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'monitor_checks'
  ) then
    alter publication supabase_realtime add table public.monitor_checks;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'incidents'
  ) then
    alter publication supabase_realtime add table public.incidents;
  end if;
end $$;
